// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechBox.Databases;

#nullable disable

namespace TechBox.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20260324170707_updateSettings")]
    partial class updateSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TechBox.Models.SCCMAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SCCMActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientAction = "{00000000-0000-0000-0000-000000000001}",
                            IsEnabled = true,
                            Name = "Hardware Inventory Cycle"
                        },
                        new
                        {
                            Id = 2,
                            ClientAction = "{00000000-0000-0000-0000-000000000002}",
                            IsEnabled = true,
                            Name = "Software Inventory Cycle"
                        },
                        new
                        {
                            Id = 3,
                            ClientAction = "{00000000-0000-0000-0000-000000000003}",
                            IsEnabled = true,
                            Name = "Discovery Data Collection Cycle"
                        },
                        new
                        {
                            Id = 4,
                            ClientAction = "{00000000-0000-0000-0000-000000000010}",
                            IsEnabled = true,
                            Name = "File Collection Cycle"
                        },
                        new
                        {
                            Id = 5,
                            ClientAction = "{00000000-0000-0000-0000-000000000011}",
                            IsEnabled = false,
                            Name = "IDMIF Collection"
                        },
                        new
                        {
                            Id = 6,
                            ClientAction = "{00000000-0000-0000-0000-000000000012}",
                            IsEnabled = false,
                            Name = "Client Machine Authentication"
                        },
                        new
                        {
                            Id = 7,
                            ClientAction = "{00000000-0000-0000-0000-000000000021}",
                            IsEnabled = true,
                            Name = "Machine Policy Retrieval & Evaluation Cycle"
                        },
                        new
                        {
                            Id = 8,
                            ClientAction = "{00000000-0000-0000-0000-000000000022}",
                            IsEnabled = false,
                            Name = "Evaluate Machine Policies"
                        },
                        new
                        {
                            Id = 9,
                            ClientAction = "{00000000-0000-0000-0000-000000000023}",
                            IsEnabled = false,
                            Name = "Refresh Default MP Task"
                        },
                        new
                        {
                            Id = 10,
                            ClientAction = "{00000000-0000-0000-0000-000000000024}",
                            IsEnabled = false,
                            Name = "Refresh Locations Task"
                        },
                        new
                        {
                            Id = 11,
                            ClientAction = "{00000000-0000-0000-0000-000000000025}",
                            IsEnabled = false,
                            Name = "Timeout Refresh Task"
                        },
                        new
                        {
                            Id = 12,
                            ClientAction = "{00000000-0000-0000-0000-000000000026}",
                            IsEnabled = false,
                            Name = "Policy Agent Request Assignment (User)"
                        },
                        new
                        {
                            Id = 13,
                            ClientAction = "{00000000-0000-0000-0000-000000000027}",
                            IsEnabled = false,
                            Name = "User Policy Retrieval & Evaluation Cycle"
                        },
                        new
                        {
                            Id = 14,
                            ClientAction = "{00000000-0000-0000-0000-000000000031}",
                            IsEnabled = true,
                            Name = "Software Metering Generating Usage Report"
                        },
                        new
                        {
                            Id = 15,
                            ClientAction = "{00000000-0000-0000-0000-000000000032}",
                            IsEnabled = true,
                            Name = "Windows Installer Source List Update Cycle"
                        },
                        new
                        {
                            Id = 16,
                            ClientAction = "{00000000-0000-0000-0000-000000000037}",
                            IsEnabled = false,
                            Name = "Clearing Proxy Settings Cache"
                        },
                        new
                        {
                            Id = 17,
                            ClientAction = "{00000000-0000-0000-0000-000000000040}",
                            IsEnabled = false,
                            Name = "Machine Policy Agent Cleanup"
                        },
                        new
                        {
                            Id = 18,
                            ClientAction = "{00000000-0000-0000-0000-000000000041}",
                            IsEnabled = false,
                            Name = "User Policy Agent Cleanup"
                        },
                        new
                        {
                            Id = 19,
                            ClientAction = "{00000000-0000-0000-0000-000000000042}",
                            IsEnabled = false,
                            Name = "Policy Agent Validate Machine Policy/Assignment"
                        },
                        new
                        {
                            Id = 20,
                            ClientAction = "{00000000-0000-0000-0000-000000000043}",
                            IsEnabled = false,
                            Name = "Policy Agent Validate User Policy/Assignment"
                        },
                        new
                        {
                            Id = 21,
                            ClientAction = "{00000000-0000-0000-0000-000000000051}",
                            IsEnabled = false,
                            Name = "Retrying/Refreshing Certificates in AD on MP"
                        },
                        new
                        {
                            Id = 22,
                            ClientAction = "{00000000-0000-0000-0000-000000000061}",
                            IsEnabled = false,
                            Name = "Peer DP Status Reporting"
                        },
                        new
                        {
                            Id = 23,
                            ClientAction = "{00000000-0000-0000-0000-000000000062}",
                            IsEnabled = false,
                            Name = "Peer DP Pending Package Check Schedule"
                        },
                        new
                        {
                            Id = 24,
                            ClientAction = "{00000000-0000-0000-0000-000000000063}",
                            IsEnabled = false,
                            Name = "SUM Updates Install Schedule"
                        },
                        new
                        {
                            Id = 25,
                            ClientAction = "{00000000-0000-0000-0000-000000000071}",
                            IsEnabled = false,
                            Name = "NAP action"
                        },
                        new
                        {
                            Id = 26,
                            ClientAction = "{00000000-0000-0000-0000-000000000101}",
                            IsEnabled = false,
                            Name = "Hardware Inventory Collection Cycle"
                        },
                        new
                        {
                            Id = 27,
                            ClientAction = "{00000000-0000-0000-0000-000000000102}",
                            IsEnabled = false,
                            Name = "Software Inventory Collection Cycle"
                        },
                        new
                        {
                            Id = 28,
                            ClientAction = "{00000000-0000-0000-0000-000000000103}",
                            IsEnabled = false,
                            Name = "Discovery Data Collection Cycle"
                        },
                        new
                        {
                            Id = 29,
                            ClientAction = "{00000000-0000-0000-0000-000000000104}",
                            IsEnabled = false,
                            Name = "File Collection Cycle"
                        },
                        new
                        {
                            Id = 30,
                            ClientAction = "{00000000-0000-0000-0000-000000000105}",
                            IsEnabled = false,
                            Name = "IDMIF Collection Cycle"
                        },
                        new
                        {
                            Id = 31,
                            ClientAction = "{00000000-0000-0000-0000-000000000106}",
                            IsEnabled = false,
                            Name = "Software Metering Usage Report Cycle"
                        },
                        new
                        {
                            Id = 32,
                            ClientAction = "{00000000-0000-0000-0000-000000000107}",
                            IsEnabled = false,
                            Name = "Windows Installer Source List Update Cycle"
                        },
                        new
                        {
                            Id = 33,
                            ClientAction = "{00000000-0000-0000-0000-000000000108}",
                            IsEnabled = true,
                            Name = "Software Updates Deployment Evaluation Cycle"
                        },
                        new
                        {
                            Id = 34,
                            ClientAction = "{00000000-0000-0000-0000-000000000109}",
                            IsEnabled = false,
                            Name = "Branch Distribution Point Maintenance Task"
                        },
                        new
                        {
                            Id = 35,
                            ClientAction = "{00000000-0000-0000-0000-000000000110}",
                            IsEnabled = false,
                            Name = "DCM Policy"
                        },
                        new
                        {
                            Id = 36,
                            ClientAction = "{00000000-0000-0000-0000-000000000111}",
                            IsEnabled = false,
                            Name = "Send Unsent State Message"
                        },
                        new
                        {
                            Id = 37,
                            ClientAction = "{00000000-0000-0000-0000-000000000112}",
                            IsEnabled = false,
                            Name = "State System Policy Cache Cleanout"
                        },
                        new
                        {
                            Id = 38,
                            ClientAction = "{00000000-0000-0000-0000-000000000113}",
                            IsEnabled = true,
                            Name = "Software Updates Scan Cycle"
                        },
                        new
                        {
                            Id = 39,
                            ClientAction = "{00000000-0000-0000-0000-000000000114}",
                            IsEnabled = false,
                            Name = "Update Store Policy"
                        },
                        new
                        {
                            Id = 40,
                            ClientAction = "{00000000-0000-0000-0000-000000000115}",
                            IsEnabled = false,
                            Name = "State System Policy Bulk Send High"
                        },
                        new
                        {
                            Id = 41,
                            ClientAction = "{00000000-0000-0000-0000-000000000116}",
                            IsEnabled = false,
                            Name = "State System Policy Bulk Send Low"
                        },
                        new
                        {
                            Id = 42,
                            ClientAction = "{00000000-0000-0000-0000-000000000120}",
                            IsEnabled = false,
                            Name = "AMT Status Check Policy"
                        },
                        new
                        {
                            Id = 43,
                            ClientAction = "{00000000-0000-0000-0000-000000000121}",
                            IsEnabled = true,
                            Name = "Application Deployment Evaluation Cycle"
                        },
                        new
                        {
                            Id = 44,
                            ClientAction = "{00000000-0000-0000-0000-000000000122}",
                            IsEnabled = false,
                            Name = "Application Manager User Policy Action"
                        },
                        new
                        {
                            Id = 45,
                            ClientAction = "{00000000-0000-0000-0000-000000000123}",
                            IsEnabled = false,
                            Name = "Application Manager Global Evaluation Action"
                        },
                        new
                        {
                            Id = 46,
                            ClientAction = "{00000000-0000-0000-0000-000000000131}",
                            IsEnabled = false,
                            Name = "Power Management Start Summarizer"
                        },
                        new
                        {
                            Id = 47,
                            ClientAction = "{00000000-0000-0000-0000-000000000221}",
                            IsEnabled = false,
                            Name = "Endpoint Deployment Reevaluate"
                        },
                        new
                        {
                            Id = 48,
                            ClientAction = "{00000000-0000-0000-0000-000000000222}",
                            IsEnabled = false,
                            Name = "Endpoint AM Policy Reevaluate"
                        },
                        new
                        {
                            Id = 49,
                            ClientAction = "{00000000-0000-0000-0000-000000000223}",
                            IsEnabled = false,
                            Name = "External Event Detection"
                        });
                });

            modelBuilder.Entity("TechBox.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "isInitialSetup",
                            Value = "true"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ldap_path",
                            Value = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
